messenger4j:
  appSecret: 5b52301b7e5b68f4108aa052a53588f6
  verifyToken : EAAB9FdaFn3cBACS3K5tijYOWmoD6TKMeU3xTj11yoxuWCMeNEUH4zqkpIa4B73ZBVcDalOvv6pZCGzlxCkrdpuYzVvGMp6GKFqMuEZC1uKZCNbSLUhZCxgdufJRGBi0nUH57qKvKnVSffZCmCKy2ZAvIBhnfdqZAkGt3ZAyK1oy1LBQZDZD
  pageAccessToken: EAACEdEose0cBAAR0k3j9m3gHrcNMT5ZBZArGdebf8Rpd0RCXCiHsbZCWwzdNhcyaXeZBoo3AZAIM1dEDRNvsHV0q22q5escRJkYJIH96Nv8iv9mwPCYVq0qxaYPtjioZCGJSdLvqnQYtBAhnZBkV198C7cO1ZA1ngbjczo5uyvc6GPR8WtspPCJKE7hKOlCMvYEZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
