messenger4j:
  appSecret: 7041ee2e3bad1ef2a508a2ba07ea82b5
  verifyToken : EAAFHcFqMZAVoBAP3jbf1TsFygcr9tSQFvfP8DyWOgWQmK4ZCwX9FqPZAIrKqmQNQxvs20jRQCyMLoBkMemSZCIZB50bRJ8FjzZAoCNzZA43OAbLjroB06w89ILM47ZA4uWBxY0Y2fmIUwcTQnoE27T1lDZB7ZCnR5VGhfqSpg9pkJqZAAZDZD
  pageAccessToken: test@12345

logging:
  level:
    com:
      github:
        messenger4j: INFO
