messenger4j:
  appSecret: 7041ee2e3bad1ef2a508a2ba07ea82b5
  verifyToken : EAACEdEose0cBAHQuJuWTKBaNzI422TQVKQrPx67sVik6MOTfhznZAGIrWQCyBcDGDTIBMwu9BvcJpLGLDxUd1AZBW39Sc0TXmvnKd4D3I6muOuwNR0r89p9b6ZBL8fE4txcSyedvB7ZAMVRx6wpb72bBw8teYC0PZCmx9E1XbHuj7deCZBYjkTSpxMoxoB81DZCdzRzxxBt4AZDZD
  pageAccessToken: test@12345

logging:
  level:
    com:
      github:
        messenger4j: INFO
