messenger4j:
  appSecret: 5b52301b7e5b68f4108aa052a53588f6
  verifyToken : EAAB9FdaFn3cBACS3K5tijYOWmoD6TKMeU3xTj11yoxuWCMeNEUH4zqkpIa4B73ZBVcDalOvv6pZCGzlxCkrdpuYzVvGMp6GKFqMuEZC1uKZCNbSLUhZCxgdufJRGBi0nUH57qKvKnVSffZCmCKy2ZAvIBhnfdqZAkGt3ZAyK1oy1LBQZDZD
  pageAccessToken: EAACEdEose0cBAPIdFiY6N4rZAbepb3EFOVLaLHWVgPleanpMdqQcbOGGrgeaXZCXcow5eVuYGvHUZAHYYnQujzZBPEClqlIDCLeQJTWZC4CeVBsy4S46lfAZCaOhfYgM3ZAVE13KmVYa8yz0gpPK4T5yCIasKBj5sJjZAD7fTFMypGQcSlZCDdUFoZCa2pSc3K77xQ2OlVoBmhNwZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
