messenger4j:
  appSecret: 5b52301b7e5b68f4108aa052a53588f6
  verifyToken : EAAB9FdaFn3cBACS3K5tijYOWmoD6TKMeU3xTj11yoxuWCMeNEUH4zqkpIa4B73ZBVcDalOvv6pZCGzlxCkrdpuYzVvGMp6GKFqMuEZC1uKZCNbSLUhZCxgdufJRGBi0nUH57qKvKnVSffZCmCKy2ZAvIBhnfdqZAkGt3ZAyK1oy1LBQZDZD
  pageAccessToken: test@12345

logging:
  level:
    com:
      github:
        messenger4j: INFO
